### ISSUE TITLE
HVAC Device

### ISSUE THREAD

**Issue by jappyjan** [dawidchyrzynski/arduino-home-assistant#1]
Can you add an HVAC Device class?

**Comment by dawidchyrzynski** [comment]
Sure, I will add support for HVAC within two weeks. I need to research it first.

**Comment by dawidchyrzynski** [comment]
Hi @jappyjan 

The implementation will take longer than I expected. Compiled library exceeds the flash size of the Arduino Uno. I will need to optimize the codebase a little bit.

**Comment by dawidchyrzynski** [comment]
Hi @jappyjan

HVAC is already available on the `develop` branch. You can test it before it will be released as 1.2.0.
