### ISSUE TITLE
expected ')' before '&' token

### ISSUE THREAD

**Issue by duckati** [dawidchyrzynski/arduino-home-assistant#100]
I get this error simply by checking the "nano33iot" example.
I checked with both Arduino Create and Arduino IDE 1.8.19.
Following the log:

Arduino: 1.8.19 (Windows 10), Board: "Arduino NANO 33 IoT"

In file included from C: \ Arduino \ libraries \ home-assistant-integration \ src \ device-types \ HASwitch.cpp: 5: 0:

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 23: 18: error: expected ')' before '&' token

     HAMqtt (Client & netClient, HADevice & device);

                  ^

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 224: 5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client & _netClient;

     ^ ~~~~~

     DNSClient

In file included from C: \ Arduino \ libraries \ home-assistant-integration \ src \ device-types \ HAFan.cpp: 4: 0:

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 23: 18: error: expected ')' before '&' token

     HAMqtt (Client & netClient, HADevice & device);

                  ^

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 224: 5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client & _netClient;

     ^ ~~~~~

     DNSClient

In file included from C: \ Arduino \ libraries \ home-assistant-integration \ src \ device-types \ HABinarySensor.cpp: 5: 0:

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 23: 18: error: expected ')' before '&' token

     HAMqtt (Client & netClient, HADevice & device);

                  ^

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 224: 5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client & _netClient;

     ^ ~~~~~

     DNSClient

In file included from C: \ Arduino \ libraries \ home-assistant-integration \ src \ device-types \ HASensor.cpp: 8: 0:

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 23: 18: error: expected ')' before '&' token

     HAMqtt (Client & netClient, HADevice & device);

                  ^

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 224: 5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client & _netClient;

     ^ ~~~~~

     DNSClient

In file included from C: \ Arduino \ libraries \ home-assistant-integration \ src \ device-types \ BaseDeviceType.cpp: 2: 0:

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 23: 18: error: expected ')' before '&' token

     HAMqtt (Client & netClient, HADevice & device);

                  ^

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 224: 5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client & _netClient;

     ^ ~~~~~

     DNSClient

In file included from C: \ Arduino \ libraries \ home-assistant-integration \ src \ device-types \ HAHVAC.cpp: 5: 0:

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 23: 18: error: expected ')' before '&' token

     HAMqtt (Client & netClient, HADevice & device);

                  ^

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 224: 5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client & _netClient;

     ^ ~~~~~

     DNSClient

In file included from C: \ Arduino \ libraries \ home-assistant-integration \ src \ device-types \ HACover.cpp: 4: 0:

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 23: 18: error: expected ')' before '&' token

     HAMqtt (Client & netClient, HADevice & device);

                  ^

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 224: 5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client & _netClient;

     ^ ~~~~~

     DNSClient

In file included from C: \ Arduino \ libraries \ home-assistant-integration \ src \ device-types \ HATagScanner.cpp: 5: 0:

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 23: 18: error: expected ')' before '&' token

     HAMqtt (Client & netClient, HADevice & device);

                  ^

c: \ arduino \ libraries \ home-assistant-integration \ src \ hamqtt.h: 224: 5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client & _netClient;

     ^ ~~~~~

     DNSClient

exit status 1

Error when compiling for the Arduino NANO 33 IoT board.

**Comment by dawidchyrzynski** [comment]
https://github.com/dawidchyrzynski/arduino-home-assistant/issues/82
