### ISSUE TITLE
Add support to select the device_class for Sensors and Binary_Sensors

### ISSUE THREAD

**Issue by LKuech** [dawidchyrzynski/arduino-home-assistant#11]
As descripted at the HA documentation the device_class is very helpful to automatically show the device in lovelace with the right icon and values etc.
[https://www.home-assistant.io/integrations/binary_sensor/#device-class](url)

I guess this one is easy for you, as this is technically done by just setting the "device_class" (i.e. to "illuminance") inside the mqtt configuration topic.

also it would be very nice to have the "icon" field accessible as well. It allows to receive normal icon definitions like "mdi:lightbulb" etc. This way you can select the icon that lovelace should show by default from inside your arduino code... This makes it pretty much plug and play ;)

**Comment by dawidchyrzynski** [comment]
Hi @LKuech 

Please take a look at examples of the sensor and binary sensor. Both support device class as the second argument in the constructor. You can also refer to the codebase where classes are documented in more detail, e.g.: https://github.com/dawidchyrzynski/arduino-home-assistant/blob/main/src/device-types/HABinarySensor.h
