### ISSUE TITLE
Information Resquest About The Arduino and Home Assistant Integration

### ISSUE THREAD

**Issue by AbelOuellette** [dawidchyrzynski/arduino-home-assistant#122]
ArduinoHA Library Is an excellent library. I Use the library on multiple device and it work very well.
I run in an issue with my last project: 
Nature of the projet: 
The project is to control two (2) water heater for my home 

Description of my project:
I have two (2) relay that are controlled with Home Assistant 
I have 4 (four) insulated input that are monitored from  Home Assistant 
I have two (2) digital temperature probe, (ds18b20) temperature probe.

Design Specification of my project:
I made a simple Arduino program with the ArduinoHA Library.

The Arduino program report the state of the 4  insulated input in home assistant.
The Arduino program report the temperature measurement from the two ds18b20 to home assistant
The home assistant program can control the status of two relay on the circuit board.

Description of my issue
The two relay can be controlled from home assistant, no problem 
The status of only three (3) insulated input, instead of four (4) are shown in home assistant.
The temperature measurement from the ds18b20 are not shown in home assistant.

Microcontroller and circuit board: 
the pin of the arduino are connected to optocoupler and resistor. The insulated input are compatible with a voltage of 24vdc instead of 5 volt.
Microcontroller used for the project: atmega1284  with an arduino bootloader.
Connection to network: Wired Ethernet.

Communication with MQTT and test:
The circuit board work perfectly and i can monitor all function with the MQTT.fx software 
When I activate the digital input the value are shown in there relevant MQTT Topic 
The temperature measurement form the ds18b20 are shown in there relevant MQTT Topic.
the Relay can be controlled from the  MQTT.fx software using the relevant MQTT Topic.
Note: i have plenty of Ram and other resource available on the  atmega1284 microcontroller.

  Thank you for your help 
This is the code, I use for the Atmega1284 microcontroller with arduino bootloader.

![Electrical_Boiler](https://user-images.githubusercontent.com/21963307/210302890-74bee3ed-b7ff-429d-9fc0-690c958e728a.png)

#include <Ethernet.h>
#include <ArduinoHA.h>
#include <OneWire.h>
#include <DallasTemperature.h>
#include <Arduino.h>

#define ARDUINOHA_DEBUG;
//Input and LED Indicator Declaration

const int DigitalInputpin1 = 20; //Digital Input (Isolated Input) Arduino: 20 ,Digital Output on the Microcontroler:
const int DigitalInputpin2 = 21; //Digital Input (Isolated Input) Arduino: 21 ,Digital Output on the Microcontroler:

int DigitalInput1 = LOW;
int DigitalInputold1 = LOW;

int DigitalInput2 = LOW;
int DigitalInputold2 = LOW;

// Relay Control 

const int RelayPin1 = 24;
const int RelayPin2 = 25;
const int RelayPin3 = 26;
const int RelayPin4 = 27;
const int RelayPin5 = 28;
const int RelayPin6 = 29;
int RelayState1 = LOW;
int RelayState2 = LOW;

// Data wire is plugged into digital pin 2 on the Arduino
OneWire oneWireA (0) ;
OneWire oneWireB (1) ;

// Setup a oneWire instance to communicate with any OneWire device

// Pass oneWire reference to DallasTemperature library
DallasTemperature sensorsA (&oneWireA) ;
DallasTemperature sensorsB (&oneWireB) ;

float tempSensorsA =0;
float tempSensorsB =0;

byte mac[] = {0x00, 0x10, 0xFA, 0x5F, 0x38, 0xB3};

EthernetClient client;
HADevice device;
HAMqtt mqtt(client, device);
unsigned long lastUpdateAt = 0;
unsigned long lastUpdateAtTempA = millis();
unsigned long lastReadAt1 = millis();
unsigned long lastReadAt2 = millis();
unsigned long lastAvailabilityToggleAt1 = millis();

// "myUptime" is unique ID of the sensor. You should define your own ID.
HASwitch led1("WaterHeaterAA");
HASwitch led2("WaterHeaterBB");
HABinarySensor sensor1("HeaterAA");
HABinarySensor sensor2("HeaterBB");
HABinarySensor sensor3("HeaterCC");
HABinarySensor sensor4("HeaterDD");
HASensorNumber tempSensorA  ("TempAA");
HASensorNumber tempSensorB  ("TempBB");

void setup() {
   byte i;
  byte dsAddress[8];

  Serial.begin( 9600 );
  Serial.println("Roof Temperature");
  Serial.println("MQTT Arduino Demo"); //Serial Print The Following "MQTT Basement Temperature Measurement" on the Console
    // you don't need to verify return status
  oneWireA.reset_search();  // Start the search with the first device
  if( !oneWireA.search(dsAddress) )
 {
   Serial.println( "none found. Using default MAC address." );
  } else {
   Serial.println( "success. Setting MAC address:" );
    Serial.print( " DS18B20 ROM  =" );
    for( i = 0; i < 8; i++)
    {
      Serial.write(' ');
      Serial.print( dsAddress[i], HEX );
    }
    Serial.println();
    
    // Offset array to skip DS18B20 family code, and skip mac[0]
   mac[1] = dsAddress[3];
   mac[2] = dsAddress[4];
   mac[3] = dsAddress[5];
   mac[4] = dsAddress[6];
   mac[5] = dsAddress[7];
  }
  
  Serial.print( " Ethernet MAC =" );
  for( i = 0; i < 6; i++ )
  {
    Serial.write( ' ' );
    Serial.print( mac[i], HEX );
 }
  Serial.println();

  // start the Ethernet connection:
  Ethernet.init(4);  // use pin 4 for Ethernet CS
 Serial.print( "Initializing Ethernet..." );

    Ethernet.begin(mac);

  Serial.print( "My IP address: " );
  Serial.println( Ethernet.localIP() );

EthernetClient client;
  
  device.setUniqueId(mac, sizeof(mac)); // the input array is cloned internally
    // connection with credentials on default port 1883
    mqtt.begin("192.168.40.113", 1883, "mqttclient", "convaid");

    lastReadAt1 = millis();
    lastReadAt2 = millis();
    lastUpdateAtTempA = millis();
    lastAvailabilityToggleAt1 = millis();
   

    // set device's details (optional)
    device.setName("Electrical_Boiler");
    device.setSoftwareVersion("1.8.0");
    device.setModel("ATmega2560");
  
    device.enableSharedAvailability();
    device.enableLastWill();
    led1.setIcon("mdi:Relay_Board_1");
    led1.setName("My LED_1");
    led2.setIcon("mdi:Relay_Board_2");
    led2.setName("My LED_2");
    sensor1.setIcon("mdi:Switch");
    sensor1.setName("Contactor_A");
    sensor2.setIcon("mdi:Switch");
    sensor2.setName("Contactor_B");
    sensor3.setIcon("mdi:Switch");
    sensor3.setName("Contactor_C");
    sensor4.setIcon("mdi:Switch");
    sensor4.setName("Contactor_D");
    tempSensorA.setIcon("mdi:Temp");
    tempSensorA.setName("Input_Temperature");
    tempSensorA.setUnitOfMeasurement("C");
    tempSensorB.setIcon("mdi:Temp");
    tempSensorB.setName("Output_Temperature");
    tempSensorB.setUnitOfMeasurement("C");

  sensorsA.begin();
  sensorsB.begin(); 

// handle switch state
    led1.onCommand(onSwitchCommand);
    led2.onCommand(onSwitchCommand);

//Initialize the Digital Input 
pinMode (DigitalInputpin1, INPUT); // Isolated Digital Input 1
pinMode (DigitalInputpin2, INPUT); // LED Light for the status of the Validation Heating Relay 1

//Initialize the Digital Output Relay
  pinMode (RelayPin1, OUTPUT); // Relay  1 Output Pin
  pinMode (RelayPin2, OUTPUT); // Relay  2 Output Pin
  pinMode (RelayPin3, OUTPUT); // Relay  2 Output Pin
  pinMode (RelayPin4, OUTPUT); // Relay  2 Output Pin
  pinMode (RelayPin5, OUTPUT); // Relay  2 Output Pin
  pinMode (RelayPin6, OUTPUT); // Relay  2 Output Pin
}

void loop() {
        Ethernet.maintain();
        mqtt.loop();
        Inputstatus1 ();
        Inputstatus2 ();
  
// Set the Digital Input with the: DigitalInput variable
    DigitalInput1 = digitalRead (DigitalInputpin1); // Digital Input 1 (Variable: DigitalInput1)
    DigitalInput2 = digitalRead (DigitalInputpin2); // Digital Input 2 (Variable: DigitalInput2)

// Output Relay Management
//  Relay 1 , Relay 2
// Set the Digital Output with the: RelayState1 variable
    digitalWrite(RelayPin1, RelayState1);
    digitalWrite(RelayPin2, RelayState2);

sensorsA.requestTemperatures(); // Send the command to get temperatures
  tempSensorsA = sensorsA.getTempCByIndex(0);

sensorsB.requestTemperatures(); // Send the command to get temperatures
  tempSensorsB = sensorsB.getTempCByIndex(0);

  if ((millis() - lastUpdateAtTempA) > 5000) { // 1000ms debounce time
  Serial.print("Roof_Temperature_A: ");
  Serial.println(tempSensorsA);
  tempSensorA.setValue(tempSensorsA);
  
  Serial.print("Roof_Temperature_B: ");
  Serial.println(tempSensorsB);
  tempSensorB.setValue(tempSensorsB);
   lastUpdateAtTempA = millis();
   
    }

//Input Managment 

    // You can also change the state at runtime as shown below.
    // This kind of logic can be used if you want to control your switch using a button connected to the device.
    
  if ((millis() - lastReadAt1) > 30) { // read in 30ms interval
        // library produces MQTT message if a new state is different than the previous one
        sensor1.setState(DigitalInput1);
       DigitalInputold1 = sensor1.getCurrentState();
        lastReadAt1 = millis();
    }

if ((millis() - lastReadAt2) > 30) { // read in 30ms interval
        // library produces MQTT message if a new state is different than the previous one
       sensor2.setState(DigitalInput2);
        DigitalInputold2 = sensor2.getCurrentState();
        lastReadAt2 = millis();
    }
}

void Inputstatus1 (void)
{
if (DigitalInput1 != DigitalInputold1)
  {
    if (DigitalInput1 == HIGH) 
    {
    Serial.println("Digital Input 1 ON");
    }
else
{
    Serial.println("Digital Input 1 OFF");
  }
  }
    DigitalInputold1 = DigitalInput1;
}

void Inputstatus2 (void)
{
if (DigitalInput2 != DigitalInputold2)
  {
    if (DigitalInput2 == HIGH) 
    {
    Serial.println("Digital Input 2 ON");
    }
else
{
    Serial.println("Digital Input 2 OFF");
  }
  }
    DigitalInputold2 = DigitalInput2;
}
void onSwitchCommand(bool state,HASwitch* sender)
{
    // Relay for the Water Heater A
if (sender == &led1 && state == 1) 
{
 Serial.println("Water Heater A ON");
     RelayState1 = HIGH;
} 
else if (sender == &led1 && state == 0) 
{
RelayState1 = LOW;
Serial.println("Water Heater A OFF");
} 
// Relay for the Water Heater B
if (sender == &led2 && state == 1) 
{

 Serial.println("Water Heater B ON");
     RelayState2 = HIGH;
} 
else if (sender == &led2 && state == 0) 
{
RelayState2 = LOW;
Serial.println("Water Heater B OFF");
} 
sender->setState(state); // report state back to the Home Assistant
  }

**Comment by rmeissn** [comment]
I had the same issue. I raised the limit for processed devices to a higher number than 6 (default value) - `HAMqtt mqtt(client, device, 10);` (for 10 devices)
See https://github.com/dawidchyrzynski/arduino-home-assistant/issues/113#issuecomment-1323527940
