### ISSUE TITLE
Unclear function for setting state_class

### ISSUE THREAD

**Issue by jobvk** [dawidchyrzynski/arduino-home-assistant#126]
In the documentation and examples, I can't find an example of how to use `state_class`?

**Comment by pebalk** [comment]
> In the documentation and examples, I can't find an example of how to use `state_class`?

Please have a look at my new commit #128 
Should fix the missing option.

**Comment by dawidchyrzynski** [comment]
@jobvk This feature will be available in the coming version of the lib - https://github.com/dawidchyrzynski/arduino-home-assistant/pull/179
