### ISSUE TITLE
about select.ino

### ISSUE THREAD

**Issue by winterrise** [dawidchyrzynski/arduino-home-assistant#135]
Line 11  HASelect **select**("mySelect");
Line 45,46,47,48
   **select**.setOptions("Low;Medium;High"); // use semicolons as separator of options
   **select**.onCommand(onSelectCommand);

   **select**.setIcon("mdi:home"); // optional
   **select**.setName("My dropdown"); // optional

Can not use select , it will replace with myselect.

**Comment by dawidchyrzynski** [comment]
The example will be updated in the upcoming version of the library. Please refer to the linked Pull Request for more information.
