### ISSUE TITLE
MQTT Payload always contains HA Config

### ISSUE THREAD

**Issue by Blueforcer** [dawidchyrzynski/arduino-home-assistant#138]
besides HA i use the libs MQTT cleint also for other things.
if i receive a message, there is always some ha config in the payload.
in following example i only send "hallo"

hallo1097bd33921c/BTN8/config���␄�B���>5E��;_w��EY�f��R␑�␎6�&��␛�R�W��ԙb���p�ė�I␗�␎&l*�����J꣨:mb␝���W␝:l�^A���␗]۪�S�{�[�����h␇�ە��_�s␜�␗�␆{|����~��␚�␡2l␚H�^��*'␑�m���␘�Fӟ;>��,��␅�Lg2̹@�>���7�j���mrG�q_��^ A�␎=^�0�t��GUjIxV��T

i cannot find my error:)

**Comment by dawidchyrzynski** [comment]
Hi @Blueforcer,

Please provide the source code.

**Comment by Blueforcer** [comment]
Hi @dawidchyrzynski 

there is nothing wich could change my payload
![image](https://user-images.githubusercontent.com/31169771/220128565-f06dc27a-5c4c-43c6-b006-53347f7bac1c.png)

Output is
![image](https://user-images.githubusercontent.com/31169771/220128628-3b902424-aeed-48f9-9025-b1cc486472c3.png)

you can find my sourcecode here:
https://github.com/Blueforcer/SmartPusher/blob/17aa11c9569d6068e79de34a6582efa5960752d0/src/MqttManager.cpp#L90

**Comment by dawidchyrzynski** [comment]
The `onMessage` callback function is designed to handle both external and internal messages that are processed by the library. However, if the message topic does not meet your requirements, it should be ignored. Therefore, it is important to implement the necessary checks to filter out irrelevant messages. It's expected behaviour. See the documentation: https://dawidchyrzynski.github.io/arduino-home-assistant/documents/api/core/ha-mqtt.html

**Comment by Blueforcer** [comment]
I already filter the topics.
While the topic is correct, the payload is still mixed up, it contains my sended message AND some internal messages.
![image](https://user-images.githubusercontent.com/31169771/220132610-3c9a238d-a91a-4f2a-92d0-fd8ea6482c03.png)

**Comment by Blueforcer** [comment]
I already filter my topics.
While the topic is correct the payload is still messed up. It contains my message (green box) AND some internal data
![image](https://user-images.githubusercontent.com/31169771/220133890-b1ab4c53-4852-445d-8307-3d9ecf312ab3.png)

**Comment by dawidchyrzynski** [comment]
@Blueforcer That's due to an invalid conversion of uint8_t to String. The payload buffer doesn't contain a null terminator.
