### ISSUE TITLE
No configuration for expire_after

### ISSUE THREAD

**Issue by PM04290** [dawidchyrzynski/arduino-home-assistant#159]
Some times, for example for push button or else, it would be interesting to set **expire_after** parameter on mqtt configuration, for sensor and binary_sensor; as it is possible to do in the configuration of zigbee2mqtt, for example: https://www.zigbee2mqtt.io/guide/configuration/devices-groups.html

real case example :
push button who send pressed time : 350ms, 1500ms, 5200ms, etc...
actually if i want to do the same function i must send a 0 (zero) value after few millisecond, so expire_after in HA save this action and is better for mqtt bandwidth :)

**Comment by dawidchyrzynski** [comment]
This feature will be available in the upcoming version of the library. Please refer to the linked Pull Request for more information.

**Comment by PM04290** [comment]
As there were no more modifications I had to Fork the library, I added **expire_after** and **state_class**; but the most important thing was changing the mqtt connection.
I would prefer to use this library if it will continue to live.

**Comment by PM04290** [comment]
Because of multiple disconnect callback when mqtt id OFF, i must put comment on callback process; only when pubsubclient detect them, with adding onDisconnect callback.
![image](https://github.com/dawidchyrzynski/arduino-home-assistant/assets/65124804/b68773d1-10b9-4e8e-920e-2564d70d0189)
![image](https://github.com/dawidchyrzynski/arduino-home-assistant/assets/65124804/83f092bd-3579-4998-9451-8ed6f41e51b6)
![image](https://github.com/dawidchyrzynski/arduino-home-assistant/assets/65124804/6d7127bd-13e0-4e86-adce-3a7ddea2c987)
