### ISSUE TITLE
Only 5 switchs discovered by HA on 8 declared

### ISSUE THREAD

**Issue by monsieurrouge** [dawidchyrzynski/arduino-home-assistant#162]
8 differents switchs configured with differents id and name.

Only 5 are discovered by HA.

maybe an issue with discovery message ?

Use with Pico2040.

**Comment by justind000** [comment]
Check out the maxDevicesTypesNb=6 parameter of the class constructor.

https://dawidchyrzynski.github.io/arduino-home-assistant/documents/api/core/ha-mqtt.html
