### ISSUE TITLE
Feature Request:  HASelect.getOption

### ISSUE THREAD

**Issue by netmindz** [dawidchyrzynski/arduino-home-assistant#163]
It would  be very useful to be able to get the string value of the current state without needing to have a separate array to map getCurrentState() back to the values used in setOptions

select.setOptions("Low;Medium;High");

want to `Serial.printf("Current option: %s\", select.getOption());` rather than needing `options = {"Low","Medium","High"}; Serial.printf("Current option: %s\", options[select.getCurrentState()]);`

**Comment by dawidchyrzynski** [comment]
This feature will be available in the upcoming version of the library. Please refer to the linked Pull Request for more information.
