### ISSUE TITLE
Feature request: expire_after for MQTT sensors

### ISSUE THREAD

**Issue by ngolf** [dawidchyrzynski/arduino-home-assistant#171]
(Thanks for the library BTW!!, it makes things super easy!)

It would be nice if one could set the expire_after for sensor values. Unless of course there is a better way to achieve the same effect (having sensors become unavailable if haven't reported to HA for a period of time), but I (newbie) couldn't find one.

**Comment by dawidchyrzynski** [comment]
This feature will be available in the upcoming version of the library. Please refer to the linked Pull Request for more information.
