### ISSUE TITLE
STM32Duino & STM32F4 - not working

### ISSUE THREAD

**Issue by rozrabiak** [dawidchyrzynski/arduino-home-assistant#181]
Compiles without problems, but:
```cpp
    device.setName("greenhouse");
    device.setSoftwareVersion("1.0.0");
    if(hamqtt.begin(MQTT_BROKER_ADDR,"USERNAME","PASSWORD"))
    {
      Serial.println("MQTT connected");
    }
```

begin returns TRUE but in mosquitto logs no new device/client.

**Comment by dawidchyrzynski** [comment]
@rozrabiak The MQTT connection is asynchronous. Please check the documentation and ensure the MQTT address is a reachable IP address.

https://dawidchyrzynski.github.io/arduino-home-assistant/documents/library/mqtt-advanced.html
