### ISSUE TITLE
Ethernet Board not working.

### ISSUE THREAD

**Issue by Gamer08YT** [dawidchyrzynski/arduino-home-assistant#185]
Used Board: KEYESTUDIO W5500
IC: ATMEGA328
Used Librarie: Arduino Native Ethernet.

Problem: MQTT is not connecting, Debug not working...

Code: https://gist.github.com/Gamer08YT/369364481727008ee18c31b69aea45c7

**Comment by dawidchyrzynski** [comment]
Hi Jan,

Does your router resolve "homeassistant.local" hostname to a proper IP address? Please try to use static IP instead.

------- Original Message -------

**Comment by Gamer08YT** [comment]
Perfect ;)

With the static IP address it works, thanks for your quick help.

Have it running on ESP platform via DNS, there it also runs without problems, but the static IP address is enough for me, so quickly I will not change this ;)
