### ISSUE TITLE
Is this library alive?

### ISSUE THREAD

**Issue by rschiemann1** [dawidchyrzynski/arduino-home-assistant#192]
Hi all,
seems like this library does exactly what I need, and I would really like to take it into use on a larger scale. However, I am a bit worried about its state. The main author does not seem to be active on the project and a few bugs have been reported. Is this library to be considered dead?

**Comment by dawidchyrzynski** [comment]
Hi @rschiemann1, At present, I am unable to allocate time for addressing the fixes. Most of them are relatively minor, so I may consider implementing the updates soon.

**Comment by rschiemann1** [comment]
Thanks for the super-quick answer, that tells something about current state of the library 👍
