### ISSUE TITLE
availability topic in MQTT

### ISSUE THREAD

**Issue by tomakara** [dawidchyrzynski/arduino-home-assistant#2]
Hey there!
Thanks for nice library!
Could you please add possibility for setting  availability_topic in MQTT for devices? For example if a switch or sensor is temporary not working.

**Comment by dawidchyrzynski** [comment]
Hi! 
Sure, I will add the requested feature by the end of this week.

**Comment by dawidchyrzynski** [comment]
Hi @tomakara
I have already released a new version of the lib (1.1.0). Feel free to test the availability feature. If you will find any issue please open a new ticket.

**Comment by tomakara** [comment]
Thanks man, that was a lot of work. I'm just a script kiddie but it's a nice evolution in the code. Going to try it now.

**Comment by dawidchyrzynski** [comment]
I had to refactor and simplify a few things in the codebase. Introducing new features in the future will be simpler for sure.

**Comment by tomakara** [comment]
Works like a charm!
