### ISSUE TITLE
Problem with Home assistant Auroconfiguration

### ISSUE THREAD

**Issue by Corrado-Cuneo** [dawidchyrzynski/arduino-home-assistant#20]
I use home assistant from many year.. I test your beatiful library with an Arduino Uno + Ethernet Shield... (I set IP manually and the shield connect ok to network and have correct ping response.
I'use your simple example "binary-sensor" schetch but I've no notification on home assistant of new device detected....
Any suggestion?
Is necessary additional task for connection?
Thanks!!
Corrado

**Comment by dawidchyrzynski** [comment]
Hi @Corrado-Cuneo

Please confirm if your device is successfully connecting to the MQTT broker. You can enable debug mode of the library by initializing serial port (`Serial.begin(9600);`) in your `void setup() { }` and by uncommenting `#define ARDUINOHA_DEBUG` in the https://github.com/dawidchyrzynski/arduino-home-assistant/blob/main/src/ArduinoHADefines.h file.

**Comment by Corrado-Cuneo** [comment]
Thanks!!! I've enable debug...
and I see message like this "Broker communication error"
In the Mosquito broker configuration I try to set:
anonymous: true (default is false)

And the log change to:
Connected to the broker
Publishing message with topic: homeassistant/binary_sensor/0010fa6e384a/input/config, payload length: 187
Publishing message with topic: homeassistant/binary_sensor/0010fa6e384a/input/state, payload length: 2
In HA no new device....

In my schetch I've set the Broker credential...

#define BROKER_USERNAME     "corrado" // replace with your credentials
#define BROKER_PASSWORD     "Xtgrbk2020IoT" //this is only a test password...

With this credential I've many tasmota device that work fine.
_

**Comment by dawidchyrzynski** [comment]
Hi @Corrado-Cuneo

Which version of MQTT integration do you use?

Please double-check if you have this option turned on:
<img width="948" alt="Zrzut ekranu 2021-03-23 o 11 10 39" src="https://user-images.githubusercontent.com/7567202/112130266-9a194700-8bc8-11eb-9bf9-3960543215bf.png">

You can also check if Home Assistant is able to track MQTT messages by using "Listen to a topic" feature from the MQTT integration. Type `homeassistant/binary_sensor/0010fa6e384a/input/config` topic, click "Start listening" and then reboot your device (binary sensor).
<img width="716" alt="Zrzut ekranu 2021-03-23 o 11 11 59" src="https://user-images.githubusercontent.com/7567202/112130403-bfa65080-8bc8-11eb-86ce-04202c1c0152.png">

**Comment by Corrado-Cuneo** [comment]
Hi!!
I've check you suggestion:
![MQTT Version](https://user-images.githubusercontent.com/81166618/112231305-c5d31600-8c36-11eb-804d-928c5576dea5.JPG)

![image](https://user-images.githubusercontent.com/81166618/112231379-e4391180-8c36-11eb-9a9c-048754c41893.png)

![image](https://user-images.githubusercontent.com/81166618/112232432-d71d2200-8c38-11eb-8ce0-99b5fccef61c.png)

If I set Anonimous=true

![image](https://user-images.githubusercontent.com/81166618/112232772-704c3880-8c39-11eb-9a67-fa67b29f604c.png)
But no new entity discovered by home assistant...

If I set Anonimous false
![image](https://user-images.githubusercontent.com/81166618/112233051-fc5e6000-8c39-11eb-93aa-e6086459e6d5.png)


![image](https://user-images.githubusercontent.com/81166618/112233094-0d0ed600-8c3a-11eb-90a6-66b4aeef57f5.png)

**Comment by dawidchyrzynski** [comment]
It looks like a problem with the network or mosquito, but I'm not 100% sure. Some people reported similar behavior in this here: https://github.com/eclipse/mosquitto/issues/523

Here are some ideas that may help:
* Use a different Ethernet shield (I mean the same model but a different device). The problem may be related to hardware/client ID
* Set the static IP address in `void setup()` instead of relying on DHCP
* If you have some spare router connect your PC with MQTT broker and Arduino to it and check if it solves the problem

I will do some extra research during the weekend. Please get back to me if the above solutions helped you.

**Comment by Corrado-Cuneo** [comment]
I've install a new instance of Homeassistant on RPI....
I've set static IP on my sketch...
I load the new version of the library (1.20)...
Binary sensor OK!!!
In the weekend I test the other sketch and mixed sensor and switch...
Thanks for all!!! Usefull library!!
