### ISSUE TITLE
Devices become unavailable every 15 minutes

### ISSUE THREAD

**Issue by erdeidominik99** [dawidchyrzynski/arduino-home-assistant#201]
Hello!
My devices become unavailable in HA every 15 mins, and after some seconds it reconnects.

**Comment by erkr** [comment]
I have the same, but not a fixed period. varies for a few minutes to 20 minutes. My manual MQTT implementation doesn't have this issue

**Comment by erdeidominik99** [comment]
I solved it, it was caused by my firewall, becsause the device was in a separate lan, and the tcp connection disconnected because of nat.

**Comment by erkr** [comment]
Hmm, I think fixed it as well by just adding a small delay of 5 msec in the loop(). It is running stable now for over an hour 🤞
