### ISSUE TITLE
Is it possible to subscribe to other topics not from Homeassistant

### ISSUE THREAD

**Issue by gcharles81** [dawidchyrzynski/arduino-home-assistant#215]
Hello I would like to use your library for a gateway that i would like to get it subscribed to 4 different topics from my various MQTT nodes i have and than from this gateway i set a multiple sensor node to be visible as one device in HA.

Is that possible Thanks

**Comment by dawidchyrzynski** [comment]
Yes, it's possible. See the documentation: https://dawidchyrzynski.github.io/arduino-home-assistant/documents/library/mqtt-advanced.html
