### ISSUE TITLE
Config part not registered for some items

### ISSUE THREAD

**Issue by simie7** [dawidchyrzynski/arduino-home-assistant#219]
I use 2 `HASwitch` and 6 `HASensorNumber` items.

Problem is, that only first 5 declared item's configs are registered on MQTT. When I change order in declaration, then again first 5 items have config part on MQTT. Tried to shorten descriptions, swap declarations in `setup ()` - it has no affect.

Downgraded library from `2.0.0` to `1.3.0`, slightly changed code (different constructors etc) - works as expected.

Use Arduino Mega 2560 with W5100, if it is important.

**Comment by dawidchyrzynski** [comment]
Hi @simie7,

You need to increase the default limit of types as described here: https://dawidchyrzynski.github.io/arduino-home-assistant/documents/library/device-types.html#limitations
