### ISSUE TITLE
Feature request: please add setStateClass to HASensor class and HANumber class.

### ISSUE THREAD

**Issue by gies73** [dawidchyrzynski/arduino-home-assistant#226]
Please add setStateClass to HASensor class and HANumber class. 

The Home Assistant Sensor Entity supports the ¨state_class¨ (https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes). 
The ¨state_class" of a HASensorNumber must be set to be able to use this sensor on the energy management dashboard (https://www.home-assistant.io/docs/energy/faq/#troubleshooting-missing-entities).

Thanks in advance!

**Comment by dawidchyrzynski** [comment]
Hi @gies73, this feature is already available on the `develop` branch. It will be officially released soon.
