### ISSUE TITLE
limited entities to max 5 sensors

### ISSUE THREAD

**Issue by Digital-MoBa** [dawidchyrzynski/arduino-home-assistant#265]
I try to add about 8 different sensors. I only can see in HA five of them. The rest is not reporting!
Even if i remove some and add different type of sensor. I can only see five of them in HA.
`HASwitch MQTT_activate("ESP_heater_activ");`
`HANumber MQTT_hysterrese("ESP_heater_hysterrese");`
`HANumber MQTT_maxdays("ESP_heater_maxdays");`
`HANumber MQTT_defaulttemp("ESP_heater_defaulttemp");`
`HANumber MQTT_hightemp("ESP_heater_hightemp");`
`HANumber MQTT_solltemp("ESP_heater_solltemp");`
`HABinarySensor MQTT_status("ESP_heater_on");`
`HASensor MQTT_isttemp("ESP_heater_temp");`
![MosquittoHA](https://github.com/user-attachments/assets/558a25ae-799e-44d2-b2a9-d36d34cf912e)
I check this with the MQTT Explorer and there I can see for "homeassistant" just this five topics, even if the device under it's device_id has all eight sensors.
![MQTTTopics](https://github.com/user-attachments/assets/30f73b77-f46f-4f8c-af9d-a4aa570d81d6)
What can be the problem that not all sensor ceate a HA config topic?

**Comment by dawidchyrzynski** [comment]
https://dawidchyrzynski.github.io/arduino-home-assistant/documents/library/device-types.html
