### ISSUE TITLE
multi-state-button -- HA autoconfiguration issue

### ISSUE THREAD

**Issue by Corrado-Cuneo** [dawidchyrzynski/arduino-home-assistant#27]
Hello!!!
I've test the example multi-state-button, I've this issue:
The HA Autoconfiguration detect and add the Arduino correctly but not the botton.....
Any idea?
Thanks to all!!
Corrado

**Comment by dawidchyrzynski** [comment]
Hi @Corrado-Cuneo 

Triggers are not displayed in the HA panel (that's due to HA design). You can access the button's states in the automation's editor (e.g. try to add some automation, select your device and you should see triggers in the dropdown).
