### ISSUE TITLE
HASensor.h#L73 "setStateClass" - no member

### ISSUE THREAD

**Issue by Digital-MoBa** [dawidchyrzynski/arduino-home-assistant#270]
If I add an HASensor and want to set the setStateClass I get this ERROR: 
'class HASensor' has no member named 'setStateClass'

**Comment by Digital-MoBa** [comment]
It's the same if I want to use on an ESP8266:
mqtt.setBufferSize(512); // set the buffer size to 512 bytes, default is 256 bytes
mqtt.setKeepAlive(60); // set the keep alive interval to 60 seconds, default is 15 seconds

There is the ERROR:
'class HAMqtt' has no member named 'setBufferSize'
'class HAMqtt' has no member named 'setKeepAlive'

**Comment by dawidchyrzynski** [comment]
Please upgrade the library to 2.1.0.
