### ISSUE TITLE
8 switch

### ISSUE THREAD

**Issue by Muxtaruss** [dawidchyrzynski/arduino-home-assistant#278]
Hi all!
Wrote and uploaded code for 8 switches.

`#include <Ethernet.h>
#include <ArduinoHA.h>

#define LED_PIN0            2
#define LED_PIN1            3
#define LED_PIN2            4
#define LED_PIN3            5
#define LED_PIN4            6
#define LED_PIN5            7
#define LED_PIN6            8
#define LED_PIN7            9

#define BROKER_ADDR         IPAddress(xxx,xxx,xxx,xxx)
#define BROKER_USERNAME     "xxx" // replace with your credentials
#define BROKER_PASSWORD     "xxx"

byte mac[] = {0x00, 0x10, 0xFA, 0x6E, 0x38, 0x4C};

EthernetClient client;
HADevice device(mac, sizeof(mac));
HAMqtt mqtt(client, device);

// "led" is unique ID of the switch. You should define your own ID.
HASwitch led0("led0");
HASwitch led1("led1");
HASwitch led2("led2");
HASwitch led3("led3");
HASwitch led4("led4");
HASwitch led5("led5");
HASwitch led6("led6");
HASwitch led7("led7");

void onSwitchCommand(bool state, HASwitch* sender)
{
    if (sender == &led0) {
      digitalWrite(LED_PIN0, (state ? HIGH : LOW));
        // the switch1 has been toggled
        // state == true means ON state
    } else if (sender == &led1) {
      digitalWrite(LED_PIN1, (state ? HIGH : LOW));
        // the switch2 has been toggled
        // state == true means ON state
    } else if (sender == &led2) {
      digitalWrite(LED_PIN2, (state ? HIGH : LOW));
        // the switch2 has been toggled
        // state == true means ON state
    } else if (sender == &led3) {
      digitalWrite(LED_PIN3, (state ? HIGH : LOW));
        // the switch2 has been toggled
        // state == true means ON state
    } else if (sender == &led4) {
      digitalWrite(LED_PIN4, (state ? HIGH : LOW));
        // the switch2 has been toggled
        // state == true means ON state
    } else if (sender == &led5) {
      digitalWrite(LED_PIN5, (state ? HIGH : LOW));
        // the switch2 has been toggled
        // state == true means ON state
    } else if (sender == &led6) {
      digitalWrite(LED_PIN6, (state ? HIGH : LOW));
        // the switch2 has been toggled
        // state == true means ON state
    } else if (sender == &led7) {
      digitalWrite(LED_PIN7, (state ? HIGH : LOW));
        // the switch2 has been toggled
        // state == true means ON state
    }

    sender->setState(state); // report state back to the Home Assistant
}

void setup() {
    pinMode(LED_PIN0, OUTPUT);
    pinMode(LED_PIN1, OUTPUT);
    pinMode(LED_PIN2, OUTPUT);
    pinMode(LED_PIN3, OUTPUT);
    pinMode(LED_PIN4, OUTPUT);
    pinMode(LED_PIN5, OUTPUT);
    pinMode(LED_PIN6, OUTPUT);
    pinMode(LED_PIN7, OUTPUT);

    // you don't need to verify return status
    Ethernet.begin(mac);

    // set device's details (optional)
    device.setName("Arduino UNO");
    device.setSoftwareVersion("1.0.0");

    // handle switch state
    led0.onCommand(onSwitchCommand);
    led1.onCommand(onSwitchCommand);
    led2.onCommand(onSwitchCommand);
    led3.onCommand(onSwitchCommand);
    led4.onCommand(onSwitchCommand);
    led5.onCommand(onSwitchCommand);
    led6.onCommand(onSwitchCommand);
    led7.onCommand(onSwitchCommand);
 

    led0.setName("My LED0"); // optional
    led1.setName("My LED1"); // optional
    led2.setName("My LED2");
    led3.setName("My LED3"); // optional
    led4.setName("My LED4"); // optional
    led5.setName("My LED5");
    led6.setName("My LED6"); // optional
    led7.setName("My LED7"); // optional
 
    mqtt.begin(BROKER_ADDR, BROKER_USERNAME, BROKER_PASSWORD);
}

void loop() {
    Ethernet.maintain();
    mqtt.loop();
}`

After downloading to the Arduino board, only 6 switches are displayed in the home assistant. 
Help me find the error in the code or tell me how to change the code to display 8 switches.

![8 switch](https://github.com/user-attachments/assets/3133ac78-4157-491d-8ef5-e5162bc344dc)

**Comment by dawidchyrzynski** [comment]
Hi @Muxtaruss,

You need to increase the limit of device types as described here: https://dawidchyrzynski.github.io/arduino-home-assistant/documents/library/device-types.html#limitations
