### ISSUE TITLE
MQTT message sending error?

### ISSUE THREAD

**Issue by sanko78** [dawidchyrzynski/arduino-home-assistant#42]
Hi!
There are two devices that are ESP32 controlled and have sensors on them (Radar, temperature / humidity, LUX etc).
With a previous "home-assistant-integration" library, HA recognized the sensors well and I also received data from them.

"homeassistant / sensor / device MAC address / lux / value"

I upgraded to the "arduino-home-assistant-main" library because the previous version did not include a motion sensor (radar) sensor.
However, it sends the data like this:

"homeassistant / sensor / device MAC address / lux / state"

The HA thus incorrectly recognizes the MQTT sensors (MQTT Sensor
  sensor.mqtt_sensor_4 (this would be the temperature sensor)) because the end of the message is "state" instead of "value"

Could it be improved?
Or do you know what you need to set in HA to recognize the sensors again?
Thanks
![new2](https://user-images.githubusercontent.com/85074357/120114602-2f642900-c180-11eb-9c27-e0b18895d80b.jpg)
![old2](https://user-images.githubusercontent.com/85074357/120114603-2ffcbf80-c180-11eb-9df4-7855779fdc1e.jpg)

**Comment by dawidchyrzynski** [comment]
This feature/fix will be implemented as part of the new major release - see #81
