### ISSUE TITLE
state_class in sensors

### ISSUE THREAD

**Issue by Sampozzo** [dawidchyrzynski/arduino-home-assistant#56]
Hello,
i'm testing some sensors like DHT22 for temperature and humidity, and i noticed that on the mqtt config topic is missing "state_class":"measurement": 

https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes

Maybe you can create a function setStateClass() like you did setDeviceClass();

By now i hardcoded it in HASensor.cpp

line 167:
`size += 28;`

line 211:
```
static const char Prefix[] PROGMEM = {",\"state_class\":\"measurement\""};

DeviceTypeSerializer::mqttWriteConstCharField(Prefix,"", false);
```

but i would prefer to stay updated with your lib.

Thank you very much.

**Comment by dawidchyrzynski** [comment]
This feature/fix will be implemented as part of the new major release - see #81
