### ISSUE TITLE
autoreset switch

### ISSUE THREAD

**Issue by leonardpitzu** [dawidchyrzynski/arduino-home-assistant#59]
I have a short question - i have a switch which needs to be set by MQTT but resets itself after a while (about 2 seconds). How can i reflect back the state of the switch over MQTT so that the switch in HA shows back the OFF state.
For your information: it's an electronic door lock which has a button. Once pressed it stays open for about 2 seconds and then goes back to the locked state.

**Comment by romoloman** [comment]
The switch component has a method called setState
bool HASwitch::setState(bool state, bool force)
You need to use it when resetting the switch locally.

**Comment by leonardpitzu** [comment]
Thank you!
