### ISSUE TITLE
Know which HACover triggered a callback

### ISSUE THREAD

**Issue by tom2199** [dawidchyrzynski/arduino-home-assistant#68]
Hello, firstly thanks a ton for this library! 
I have 8 covers within my sketch, and I want them all to point to the same callback because I want to avoid writing the same function 8 times. With HASwitch, a pointer to the instance which called the callback is provided (as discussed here: https://github.com/dawidchyrzynski/arduino-home-assistant/issues/48) but it seems that's not the case with HACover.
Is there another way to do this or could that functionality be implemented?

Thanks in advance

**Comment by dawidchyrzynski** [comment]
This feature/fix will be implemented as part of the new major release - see #81
