### ISSUE TITLE
MQTT LWT behaviour after HA restart 

### ISSUE THREAD

**Issue by sgurgul** [dawidchyrzynski/arduino-home-assistant#70]
The LWT feature works great (marks sensors as Unavailable) but only until HA is restarted.
With HA restart (Arduino device remaining OFF) sensors are immediately available again with their last known value measured before Arduino was shutdown.

Is it an expected behaviour ?

My feeling was like it should remain unavailable after HA restart, as long as Arduino is OFF. Is there any way to achieve it ?

**Comment by dawidchyrzynski** [comment]
This feature/fix will be implemented as part of the new major release - see #81
