### ISSUE TITLE
HAMqtt.h error - Client does not name a type

### ISSUE THREAD

**Issue by Friend-Or-F0H** [dawidchyrzynski/arduino-home-assistant#75]
Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "Arduino NANO 33 IoT"

Header lines used:

#include <ArduinoBLE.h>
#include <WiFiNINA.h>
#include <ArduinoHA.h>
#include <OneWire.h>

#define LED_PIN                  13
#define BROKER_ADDR       IPAddress(192,168,0,17)
#define WIFI_SSID               "$myNetworkSSID"
#define WIFI_PASSWORD   "$myNetworkPASS"

WiFiClient client;
HADevice device;
HAMqtt mqtt(client, device);

Errors below:

In file included from M:\Basso\Documents\Arduino\libraries\home-assistant-integration\src\device-types\HAFan.cpp:4:0:

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:23:18: error: expected ')' before '&' token

     HAMqtt(Client& netClient, HADevice& device);

                  ^

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:224:5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client& _netClient;

     ^~~~~~

     DNSClient

In file included from M:\Basso\Documents\Arduino\libraries\home-assistant-integration\src\device-types\HASensor.cpp:8:0:

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:23:18: error: expected ')' before '&' token

     HAMqtt(Client& netClient, HADevice& device);

                  ^

In file included from M:\Basso\Documents\Arduino\libraries\home-assistant-integration\src\device-types\HACover.cpp:4:0:

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:23:18: error: expected ')' before '&' token

     HAMqtt(Client& netClient, HADevice& device);

                  ^

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:224:5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client& _netClient;

     ^~~~~~

     DNSClient

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:224:5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client& _netClient;

     ^~~~~~

     DNSClient

In file included from M:\Basso\Documents\Arduino\libraries\home-assistant-integration\src\device-types\HABinarySensor.cpp:5:0:

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:23:18: error: expected ')' before '&' token

     HAMqtt(Client& netClient, HADevice& device);

                  ^

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:224:5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client& _netClient;

     ^~~~~~

     DNSClient

In file included from M:\Basso\Documents\Arduino\libraries\home-assistant-integration\src\device-types\BaseDeviceType.cpp:2:0:

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:23:18: error: expected ')' before '&' token

     HAMqtt(Client& netClient, HADevice& device);

                  ^

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:224:5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client& _netClient;

     ^~~~~~

     DNSClient

In file included from M:\Basso\Documents\Arduino\libraries\home-assistant-integration\src\device-types\HATriggers.cpp:5:0:

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:23:18: error: expected ')' before '&' token

     HAMqtt(Client& netClient, HADevice& device);

                  ^

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:224:5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client& _netClient;

     ^~~~~~

     DNSClient

In file included from M:\Basso\Documents\Arduino\libraries\home-assistant-integration\src\device-types\HATagScanner.cpp:5:0:

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:23:18: error: expected ')' before '&' token

     HAMqtt(Client& netClient, HADevice& device);

                  ^

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:224:5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client& _netClient;

     ^~~~~~

     DNSClient

In file included from M:\Basso\Documents\Arduino\libraries\home-assistant-integration\src\device-types\HASwitch.cpp:5:0:

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:23:18: error: expected ')' before '&' token

     HAMqtt(Client& netClient, HADevice& device);

                  ^

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:224:5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client& _netClient;

     ^~~~~~

     DNSClient

In file included from M:\Basso\Documents\Arduino\libraries\home-assistant-integration\src\device-types\HAHVAC.cpp:5:0:

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:23:18: error: expected ')' before '&' token

     HAMqtt(Client& netClient, HADevice& device);

                  ^

m:\basso\documents\arduino\libraries\home-assistant-integration\src\hamqtt.h:224:5: error: 'Client' does not name a type; did you mean 'DNSClient'?

     Client& _netClient;

     ^~~~~~

     DNSClient

exit status 1

Error compiling for board Arduino NANO 33 IoT.

**Comment by Omnipius** [comment]
I am experiencing an identical error using an Arduino Uno WiFi Rev2.

**Comment by sushukka** [comment]
With Nano 33 IoT downgrade your Arduino SAM board libraries to 18. Same with WifiNINA software libraries -> 18.1.

**Comment by dawidchyrzynski** [comment]
This feature/fix will be implemented as part of the new major release - see #81
