### ISSUE TITLE
ADD: Hostname support for broker address

### ISSUE THREAD

**Issue by LKuech** [dawidchyrzynski/arduino-home-assistant#8]
As far as I understand it is just possible to use the ip address so far. A Hostname support would make sense from my point of view.

**Comment by dawidchyrzynski** [comment]
Hi @LKuech 

Sure, I will research this and implement it soon.

**Comment by dawidchyrzynski** [comment]
Hi @LKuech  

This feature is already available on the `develop` branch. Please let me know if all works as expected.
