### ISSUE TITLE
Arduino cycle restart - limit of values?

### ISSUE THREAD

**Issue by proasnet** [dawidchyrzynski/arduino-home-assistant#86]
Hello, I made some projects with this library. All working fine, but the last project has more values, and library restarting cpu in cycle.
I try comment all library codes and other working.
Now, in project is 25 analog sensors and 7 binary sensors.
Have you any idea, where may be a problem?
Thank you very much

**Comment by dawidchyrzynski** [comment]
Hi @proasnet,

It sounds like you're hitting the resources limit (RAM). Which platform do you use?

**Comment by proasnet** [comment]
Hello. I found problem. Some values was declared as byte or unsigned long
int. I found, that your library does not support this types, only int,
float or bool.
This restarts the arduino.
Long int I must declare as float and byte as int and work fine.
Thank you.

Dne ne 3. 7. 2022 18:46 uživatel Dawid Chyrzyński ***@***.***>
napsal:
